### ISSUE TITLE
Can this code run on TPU?

### ISSUE THREAD

**Issue by huynq55** [Hwhitetooth/jax_muzero#1]
Hello, I'm not so good in programming. Just want to ask. Can this code run on TPU?

**Comment by Hwhitetooth** [comment]
Hi @huynq55,

Thank you for the question!

I never tried but I think it should work. JAX can run on CPUs, GPUs, and TPUs without any change to the code so I guess this code should work on TPUs just fine.

**Comment by huynq55** [comment]
I tested it on google colab. It looks like the code doesn't recognize the TPU. Here is the log:

== Status ==
Current time: 2022-03-09 05:03:25 (running for 00:00:00.12)
Memory usage on this node: 1.2/12.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs, 0.0/7.21 GiB heap, 0.0/3.61 GiB objects
Result logdir: /root/ray_results/breakout
Number of trials: 1/1 (1 PENDING)
+------------------------+----------+-------+
| Trial name             | status   | loc   |
|------------------------+----------+-------|
| Experiment_3fefb_00000 | PENDING  |       |
+------------------------+----------+-------+


(scheduler +7s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(scheduler +7s) Error: No available node types can fulfill resource request {'GPU': 1.0, 'CPU': 1.0}. Add suitable node types to this cluster to resolve this issue.

**Comment by Hwhitetooth** [comment]
Ray was requesting a GPU resource that did not exist. I'm not sure how well Ray supports TPU though. Maybe try removing all Ray dependencies?
