### ISSUE TITLE
[Question] What's the motivation for scaling the gradient?

### ISSUE THREAD

**Issue by hr0nix** [Hwhitetooth/jax_muzero#2]
Hello!

I've noticed that the gradient is being scaled by 0.5 after every model step:

https://github.com/Hwhitetooth/jax_muzero/blob/b8ab36251d22e0246d61514841ba17a22f4b2a36/algorithms/agents.py#L116-L120

Can you clarify the motivation for that? Are you aware of any experimental results that suggest that it's helpful?

Thanks in advance!

**Comment by uduse** [comment]
@hr0nix This is mentioned in MuZero's paper. They scale the graient in two places. Before dynamics function scale by $1/K$ and between each dynamics function scale by $1/2$.

**Comment by hr0nix** [comment]
Thanks for the answer! I've seen it but cannot understand the motivation for 1/2 scaling. Was hoping you can provide some insight.

**Comment by uduse** [comment]
@hr0nix I am not sure about the motivation too. My simple intuition is that targets with larger $k$ is less reliable.

**Comment by Hwhitetooth** [comment]
Hi folks, sorry for being late to the discussion. I just followed the MuZero paper and its pseudocode. Honestly, I don't have a good explanation for the gradient scaling, either.
