### ISSUE TITLE
What are differences to EfficientZero?

### ISSUE THREAD

**Issue by dimarkov** [Hwhitetooth/jax_muzero#4]
Hi there, I am wondering in which way your implementation differs from EfficientZero. Obviosuly the repo is named MuZero, but when I go to network specifications you define networks in haiku as EfficientZero. This suggets that this is actually EZ model, but it seems that the performance is slightly worse when compared to official results from the paper. That is why I am asking this, would just like to know what else is missing from the implementation. Cheers!

**Comment by Hwhitetooth** [comment]
Sorry for the late reply!

The architecture was copied from the EfficientZero paper indeed. But all of the other algorithmic improvements are not implemented. Namely, the self-supervised representation learning loss, the value prefix trick, and the model-based off-policy correction were not implemented in this repo. These missing parts explain the performance gap.
